### ISSUE TITLE
apt-get command not working

### ISSUE THREAD

**Issue by nbfigueroa** [PickNikRobotics/boost_sml#10]
Hi, 

Just FYI, this command does not work: sudo apt-get install ros-${ROS_DISTRO}-boost_sml 

The package name is actually 
 ros-${ROS_DISTRO}-boost-sml 

at least for noetic.

Would be useful to correct that in your readme file. 

Cheers!

**Comment by saiteja12-g** [comment]
Thanks @nbfigueroa
